# Generated by Django 6.0 on 2026-01-05 19:23

from django.contrib.auth import get_user_model
from django.db import migrations

def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="YourStrongPassword123",
            is_staff=True,
            is_superuser=True,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),  # adjust if your last migration number is different
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
